/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agile;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CorporateCustomerRegistration extends javax.swing.JFrame {

    private static int custID = 1;
    /**
     * Creates new form CorporateCustomerRegistration
     */
    public CorporateCustomerRegistration() {
        initComponents();
        jtfCustomerID.setText("CR" + String.format("%04d", custID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbCompanyName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbCustomerID = new javax.swing.JLabel();
        jlbConfirmPassword = new javax.swing.JLabel();
        jlbCustomerName = new javax.swing.JLabel();
        jlbContact = new javax.swing.JLabel();
        jlbCorporateName = new javax.swing.JLabel();
        jlbCorporateAddress = new javax.swing.JLabel();
        jlbPassword = new javax.swing.JLabel();
        jtfCustomerID = new javax.swing.JTextField();
        jtfCustomerName = new javax.swing.JTextField();
        jtfContact = new javax.swing.JTextField();
        jtfCorporateName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCorporateAddress = new javax.swing.JTextArea();
        jbtRegister = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jpfConfirmPass = new javax.swing.JPasswordField();
        jpfPass = new javax.swing.JPasswordField();
        jlblCompanyID = new javax.swing.JLabel();
        jtfCompanyID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jlbCompanyName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlbCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCompanyName.setText("Fiore Flowershop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jlbCompanyName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jlbTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("Corporate Customer Registration");

        jlbCustomerID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCustomerID.setText("Customer ID:");

        jlbConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbConfirmPassword.setText("Confirm Password:");

        jlbCustomerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCustomerName.setText("Name:");

        jlbContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbContact.setText("Contact No:");

        jlbCorporateName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCorporateName.setText("Corporate Name:");

        jlbCorporateAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCorporateAddress.setText("Corporate Address:");

        jlbPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbPassword.setText("Password:");

        jtfCustomerID.setEditable(false);
        jtfCustomerID.setFocusable(false);

        jtaCorporateAddress.setColumns(20);
        jtaCorporateAddress.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtaCorporateAddress.setRows(5);
        jScrollPane1.setViewportView(jtaCorporateAddress);

        jbtRegister.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtRegister.setText("Register");
        jbtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegisterActionPerformed(evt);
            }
        });

        jbtCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtCancel.setText("Cancel");
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });

        jpfConfirmPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jpfPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlblCompanyID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblCompanyID.setText("Company ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbTitle)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbCorporateAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpfPass))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlblCompanyID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbCorporateName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbCustomerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbCustomerID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbConfirmPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCustomerID)
                                    .addComponent(jtfCustomerName)
                                    .addComponent(jtfContact)
                                    .addComponent(jtfCorporateName)
                                    .addComponent(jpfConfirmPass)
                                    .addComponent(jtfCompanyID))))
                        .addGap(191, 191, 191))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCorporateName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCorporateName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCorporateAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpfConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegisterActionPerformed
        // TODO add your handling code here:
        if(checkIsNotEmpty()){
        String pass = jpfPass.getText();
        String confirmPass = jpfConfirmPass.getText();
        int i = JOptionPane.showConfirmDialog(this,getCustInfo() +"\nAre You sure?","Yes or No",JOptionPane.YES_NO_OPTION);
        
        if(i == JOptionPane.YES_OPTION){
            if(pass.equals(confirmPass)){
                JOptionPane.showMessageDialog(this,"You can login your account now","Register Success!",JOptionPane.INFORMATION_MESSAGE);
                incrementID();
                clearText();
            }else{
                JOptionPane.showMessageDialog(this,"Password and Confirm Password is not match","Not match",JOptionPane.WARNING_MESSAGE);
                jpfPass.setText("");
                jpfConfirmPass.setText("");
            }
        }
        }
    }//GEN-LAST:event_jbtRegisterActionPerformed

    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        // TODO add your handling code here:
        clearText();
    }//GEN-LAST:event_jbtCancelActionPerformed

    private void incrementID(){
        custID++;
        jtfCustomerID.setText("CR" + String.format("%04d",custID));
    }
    
    private boolean checkIsNotEmpty(){
        String emptyTextField = "";
        if(jtfCustomerName.getText().equals("")){
            emptyTextField += "\nCustomer Name";
        }
        if(jtfContact.getText().equals("")){
            emptyTextField += "\nContact Number";
        }
        if(jtfCorporateName.getText().equals("")){
            emptyTextField += "\nCorporate Name";
        }
        if(jtaCorporateAddress.getText().equals("")){
            emptyTextField += "\nCorporate Address";
        }
        if(jpfPass.getText().equals("")){
            emptyTextField += "\nPassword";
        }
        if(jpfConfirmPass.getText().equals("")){
            emptyTextField += "\nConfirm Password";
        }
        
        if(!emptyTextField.equals("")){
            JOptionPane.showMessageDialog(this,
                    "The following text field:" + emptyTextField + "\nPlease don't leave it blank",
                    "Please fill in the form",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    private String getCustInfo(){
        String info = "";
        info = "Customer Name: " + jtfCustomerName.getText() +
                "\nContact Number: " + jtfContact.getText() +
                "\nCorporate Name: " + jtfCorporateName.getText() +
                "\nCorporate Address: " + jtaCorporateAddress.getText();
        return info;
    }
    
    private void clearText(){
        jtfCustomerName.grabFocus();
        jtfCustomerName.setText("");
        jtfContact.setText("");
        jtfCorporateName.setText("");
        jtaCorporateAddress.setText("");
        jpfPass.setText("");
        jpfConfirmPass.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorporateCustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorporateCustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorporateCustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorporateCustomerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorporateCustomerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtRegister;
    private javax.swing.JLabel jlbCompanyName;
    private javax.swing.JLabel jlbConfirmPassword;
    private javax.swing.JLabel jlbContact;
    private javax.swing.JLabel jlbCorporateAddress;
    private javax.swing.JLabel jlbCorporateName;
    private javax.swing.JLabel jlbCustomerID;
    private javax.swing.JLabel jlbCustomerName;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlblCompanyID;
    private javax.swing.JPasswordField jpfConfirmPass;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JTextArea jtaCorporateAddress;
    private javax.swing.JTextField jtfCompanyID;
    private javax.swing.JTextField jtfContact;
    private javax.swing.JTextField jtfCorporateName;
    private javax.swing.JTextField jtfCustomerID;
    private javax.swing.JTextField jtfCustomerName;
    // End of variables declaration//GEN-END:variables
}
