/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agileassignment;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jitpe
 */
public class AddOrder extends javax.swing.JFrame {
    /**
     * Creates new form AddOrder
     */
    public AddOrder() {
        initComponents();
        addRowToTable();
    }

    public class Order{
        public String id;
        public String name;
        public String desc;
        public double price;
        public String type;
        public String img;
    
        public Order(String id, String name, String desc, double price, String type, String img){
            this.id = id;
            this.name = name;
            this.desc = desc;
            this.price = price;
            this.type = type;
            this.img = img;
        }
    }
    
    public ArrayList OrderList(){
        ArrayList<Order> order = new ArrayList<>();
        Order o1 = new Order("FR0000", "Orchid", "Very beautiful flower", 6.05, "bouquet", "Jack.jpg");
        Order o2 = new Order("FA0001", "Rose", "very romantic", 30.25, "floral arrangement", "Rose.jpg");
        Order o3 = new Order("FB0002", "Lily", "Very special flower", 10.95, "fresh flowers", "Lily.jpg");
        Order o4 = new Order("FK0003", "Sunflower", "Very ...", 5.55, "bouquet", "Sunflower.jpg");
        //Order o5 = new Order("FB0004", "Dongzhuo", "Sad", 8.65, "set", "flower.jpg");
        //Order o6 = new Order("FA0005", "JackBoon", "Nothing gonna change my love for u", 99.99, "alacart", "flower.jpg");
        
        order.add(o1);
        order.add(o2); 
        order.add(o3);
        order.add(o4);
        //order.add(o5);
        //order.add(o6);
        return order;
    }
    
    public void addRowToTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<Order> order = OrderList();
        Object rowData[] = new Object[6];
        
        for(int i=0; i<order.size(); i++){
            rowData[0] = order.get(i).id;
            rowData[1] = order.get(i).name;
            rowData[2] = order.get(i).desc;
            rowData[3] = order.get(i).price;
            rowData[4] = order.get(i).type;
            rowData[5] = order.get(i).img;
            
            model.addRow(rowData);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        jtfQuantity = new javax.swing.JTextField();
        jtfDate = new javax.swing.JTextField();
        jtfTime = new javax.swing.JTextField();
        jbtConfirm = new javax.swing.JButton();
        jtfCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fiore Flowershop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description", "Price(RM)", "Type", "Picture"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText(" ID           :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText(" Quantity   :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText(" Date        :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText(" Time       :");

        jtfID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIDActionPerformed(evt);
            }
        });

        jtfQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtfDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtfTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbtConfirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtConfirm.setText("Confirm");
        jbtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmActionPerformed(evt);
            }
        });

        jtfCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfCancel.setText("Cancel");
        jtfCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jbtConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfCancel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jtfQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTime))))
                .addGap(102, 102, 102))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtConfirm)
                    .addComponent(jtfCancel))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIDActionPerformed

    private void jbtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmActionPerformed
        // TODO add your handling code here:
        if(jtfID.getText().equals("") && jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - ID\n - Quantity\n - Date\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(!jtfID.getText().equals("") && jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Quantity\n - Date\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtfID.getText().equals("") && !jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - ID\n - Date\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtfID.getText().equals("") && jtfQuantity.getText().equals("") && !jtfDate.getText().equals("") && jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - ID\n - Quantity\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtfID.getText().equals("") && jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && !jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - ID\n - Quantity\n - Date", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(!jtfID.getText().equals("") && !jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Date\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(!jtfID.getText().equals("") && jtfQuantity.getText().equals("") && !jtfDate.getText().equals("") && jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Quantity\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(!jtfID.getText().equals("") && jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && !jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Quantity\n - Date", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(!jtfID.getText().equals("") && !jtfQuantity.getText().equals("") && !jtfDate.getText().equals("") && jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Time", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else if(!jtfID.getText().equals("") && !jtfQuantity.getText().equals("") && jtfDate.getText().equals("") && !jtfTime.getText().equals("")){
            JOptionPane.showMessageDialog(null, "The below messages cannot be empty!\n - Date", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Order success!", "SUCCESS!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtConfirmActionPerformed

    private void jtfCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCancelActionPerformed
        // TODO add your handling code here:
        jtfID.setText("");
        jtfQuantity.setText("");
        jtfDate.setText("");
        jtfTime.setText("");
        jtfID.requestFocus();
    }//GEN-LAST:event_jtfCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtConfirm;
    private javax.swing.JButton jtfCancel;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfQuantity;
    private javax.swing.JTextField jtfTime;
    // End of variables declaration//GEN-END:variables
}
